# -*- coding: utf-8 -*-
"""ITEP203-Most Difficult Subject for CCS BSIT 2nd Year students.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xd_exseJFgMfxRKVO-kKyUSiTDhOp-5R
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

student_df = pd.read_csv("/content/Most difficult subjects for 2nd year students during thier 2nd 2term as 1st year students-Responses.csv")
student_df.head()

# Assuming 'Choose Subject:' is the correct column name
subject_counts = student_df['Choose Subject:'].value_counts()

# Plotting a bar chart
plt.bar(subject_counts.index, subject_counts.values, color='blue')
plt.xlabel("Subjects")
plt.ylabel("Frequency")
plt.title("Chosen Subjects")
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better visibility
plt.show()

# [Does your Internet connection affect your participation during online classes?]
data = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Does your Internet connection affect your participation during online classes?]']
plt.hist(data, bins=range(int(data.min()), int(data.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Does your Internet connection affect your participation during online classes? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')  # Corrected typo here
plt.show()

# [How helpful do you find interactive activities during online classes for your learning?]
data1 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [How helpful do you find interactive activities during online classes for your learning?]']
plt.hist(data1, bins=range(int(data1.min()), int(data1.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('How helpful do you find interactive activities during online classes for your learning? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# [Do background noises significantly distract you during online classes?]
data2 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do background noises significantly distract you during online classes?]']
plt.hist(data2, bins=range(int(data2.min()), int(data2.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do background noises significantly distract you during online classes? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do power interruptions significantly disrupt your ability to study effectively at home?]
data3 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do power interruptions significantly disrupt your ability to study effectively at home?]']
plt.hist(data3, bins=range(int(data3.min()), int(data3.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do power interruptions significantly disrupt your ability to study effectively at home? (5 being Highest, 1 being Lowest.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do you encounter technical difficulties(e.g., internet connection, platform glitches))]
data4 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do you encounter technical difficulties(e.g.,internet connection,platform glitches))]']
plt.hist(data4, bins=range(int(data4.min()), int(data4.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do you encounter technical difficulties(e.g., internet connection, platform glitches)? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Have you noticed an increase in headaches or physical discomfort related to...]
data5 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Have you noticed an increase in headaches or physical discomfort  realati]']
plt.hist(data5, bins=range(int(data5.min()), int(data5.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Have you noticed an increase in headaches or physical discomfort related to... (5 being Highest, 1 being Lowest.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do you feel less connected or enraged with your classmates and instructors in online classes compared to traditional face-to-face classroom setting?]
data6 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do you feel less connected or enraged with your classmates and instructors in online classes compared to traditional face-to-face classroom setting?]']
plt.hist(data6, bins=range(int(data6.min()), int(data6.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do you feel less connected or enraged with your classmates and instructors in online classes compared to traditional face-to-face classroom setting? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do you believe that you possess necessary skills to proficiently use digital tools and software essential for academic or professional tasks?]
data7 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do you believe that you possess necessary skills to proficiently use digital tools and software essential for academic or professional tasks?]']
plt.hist(data7, bins=range(int(data7.min()), int(data7.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do you believe that you possess necessary skills to proficiently use digital tools and software essential for academic or professional tasks? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do you think that the absence of non-verbal cues(such as body language) in online classes affects the depth of understanding between you and your instructors?]
data8 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do you think that the absence of non-verbal cues(such as body language) in online classes affects the depth of undestanding between you and your instructors?]']
plt.hist(data8, bins=range(int(data8.min()), int(data8.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do you think that the absence of non-verbal cues(such as body language) in online classes affects the depth of understanding between you and your instructors? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Scenarios that affect your ability to perform your best during this academic term.
# (5 being Highest, 1 being Lowest) [Do you feel that the methods used by the instructors in online classes encourage active engagement and participation among students?]
data9 = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Do you feel that that methos used by the instructors in online classes encourage active engagement and partipation among students]']
plt.hist(data9, bins=range(int(data9.min()), int(data9.max()) + 2), align='left', rwidth=0.8, color='blue')
plt.title('Do you feel that the methods used by the instructors in online classes encourage active engagement and participation among students? (5 being Highest, 1 being Lowset.)')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

# Assuming your DataFrame columns are named appropriately
x = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [How helpful do you find interactive activities during online classes for your learning?]']
y = student_df['Scenarios that affects your ability to perform your best during this academic term.(5 being Highest, 1 being Lowset.) [Does your Internet connection affect your participation during online classes?]']

# Create a scatter plot
plt.scatter(x, y, color='blue', alpha=0.5)  # Adjust alpha for transparency if needed

# Set plot title and labels
plt.title('Scatter Plot: Interactive Activities vs Internet Connection Impact')
plt.xlabel('Interactive Activities Rating')
plt.ylabel('Internet Connection Impact Rating')

# Set x-axis and y-axis ticks to integers
plt.xticks(range(int(x.min()), int(x.max()) + 1))
plt.yticks(range(int(y.min()), int(y.max()) + 1))

# Show the plot
plt.show()

